#!/bin/bash
# Smithery Publish Script — Run after: smithery auth login
# Generated by publish-smithery.py

set -e

echo "Publishing 9 MCP servers to Smithery..."
echo ""

echo ">>> Publishing JSON Toolkit MCP..."
smithery mcp publish "https://json-toolkit-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/json-toolkit-mcp"
echo "  Done: JSON Toolkit MCP"
echo ""

echo ">>> Publishing Regex Engine MCP..."
smithery mcp publish "https://regex-engine-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/regex-engine-mcp"
echo "  Done: Regex Engine MCP"
echo ""

echo ">>> Publishing Color Palette MCP..."
smithery mcp publish "https://color-palette-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/color-palette-mcp"
echo "  Done: Color Palette MCP"
echo ""

echo ">>> Publishing Timestamp Converter MCP..."
smithery mcp publish "https://timestamp-converter-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/timestamp-converter-mcp"
echo "  Done: Timestamp Converter MCP"
echo ""

echo ">>> Publishing Prompt Enhancer MCP..."
smithery mcp publish "https://prompt-enhancer-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/prompt-enhancer-mcp"
echo "  Done: Prompt Enhancer MCP"
echo ""

echo ">>> Publishing OpenClaw Intel MCP..."
smithery mcp publish "https://openclaw-intel-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/openclaw-intel-mcp"
echo "  Done: OpenClaw Intel MCP"
echo ""

echo ">>> Publishing OpenClaw Fortune MCP..."
smithery mcp publish "https://openclaw-fortune-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/openclaw-fortune-mcp"
echo "  Done: OpenClaw Fortune MCP"
echo ""

echo ">>> Publishing MoltBook Publisher MCP..."
smithery mcp publish "https://moltbook-publisher-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/moltbook-publisher-mcp"
echo "  Done: MoltBook Publisher MCP"
echo ""

echo ">>> Publishing AgentForge Compare MCP..."
smithery mcp publish "https://agentforge-compare-mcp.yagami8095.workers.dev/mcp" -n "yedanyagamiai-cmd/agentforge-compare-mcp"
echo "  Done: AgentForge Compare MCP"
echo ""

echo "=== All 9 servers published! ==="
echo "Check: https://smithery.ai/servers?q=yedanyagamiai-cmd"
